### ISSUE TITLE
Error running build.sh: gl_main.c: fatal error: wglext.h No such file or directory

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#11]
Using Debian 11.

Installed all dependencies listed in the README, and when running build.sh I get aforementioned error, even though I already installed all packages providing such header.

The error pops with red letters, nevertheless process goes on for a brief while until suddenly halting shortly after with exit code 1.

Also tried copying it to src/engine directory.

Also, the previous Linux builds don't work neither because they demand a glibc version newer than what current stable branches use: the builds demand at very least version 2.32, when currently used version in distros in general is 2.31...

Could you help? Thanks.

**Comment by atsb** [comment]
The latest master branch fixes this.  I have wrapped wglext.h within a _WIN32 macro and the same for the vsync settings.

```
#ifdef _WIN32
    wglSwapIntervalEXT(v_vsync.value);
#else
    glXSwapIntervalSGI(v_vsync.value);
#endif
```

Since GNU/Linux provides glext within the OpenGL headers and libraries by default, there is no need to do anything.  It should go fine out of the box.  If it still does not, I will take a look.  On an Ubuntu system and Debian Unstable it is ok.

I don't use Debian stable, I'm on Debian Unstable and so this is why I stopped providing Linux builds, because I cannot guarantee the GLIBC version to be compatible.

**Comment by bfg01** [comment]
Git-cloned today; yes, the wglext issue was finally gone. Thanks.
