### ISSUE TITLE
[Optional]Remove SDL_GetPath for open function

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#126]

**Comment by atsb** [comment]
We would need to keep this path for macOS and BSD users where Steam either isn't possible (BSD) or not really used (macOS).  Most macOS users would take the IWAD and place it somewhere in their directory structure or in the EX+ bundle itself.

This is strictly a Windows issue and to a lesser degree, Linux.  So we should wrap up an alternative for Windows users and leave the current implementation alone for the Unix Masterrace.

**Comment by Wolf3s** [comment]
> 

So windows and Linux should be remove(or keep the SDL_Path) for me fine altough it doesn't sounds a good idea.

**Comment by atsb** [comment]
Windows should search somewhere else, every other system could keep the SDL path.  Mostly because on different distro's, do we know for 100% certainty that the path would always be identical?  Certain distro's are very liberal with the Linux Filesystem Hirearchy Standard and deviate heavily.  The SDL path on Mac always goes to the Application Support directory which is the only correct place to put these.  So if you want a different path for each, it will get very messy.

Linux users generally are smarter and know how to do certain things the way they want to.

But you can do what you want about the Steam/Gog paths.  I can't test it really because I don't use Steam and for Gog I don't use any pre-defined directory.  GOG and Steam paths should be Windows only.

**Comment by Wolf3s** [comment]
> and

Steam goes to linux also :(

**Comment by atsb** [comment]
It does.  But does it go to the same directory for steamapps across all distro's?

**Comment by Wolf3s** [comment]
> It does. But does it go to the same directory for steamapps across all distro's?

I dunno since i don´t use also but probablly no.

**Comment by atsb** [comment]
I would say, we make it clear that the steam path is for Ubuntu only.  I don't really care about other distro's and nobody is going to run steam on Red Hat, so Ubuntu it is.

**Comment by Wolf3s** [comment]
> I would say, we make it clear that the steam path is for Ubuntu only. I don't really care about other distro's and nobody is going to run steam on Red Hat, so Ubuntu it is.

We should update the readme then about this.

**Comment by atsb** [comment]
Agreed

**Comment by atsb** [comment]
I’ll look what choco does for Linux and Mac paths.  It’s probably the d_iwad stuff

**Comment by Wolf3s** [comment]
> Referenc

Fun Fact: this guy on windows wasn´t included :)

**Comment by atsb** [comment]
Feel free to do it :)

I don't really see much of a priority since EX+ right now can just be dropped into the GOG or Steam directory anyway, but you can add the feature if you wish :)

**Comment by Wolf3s** [comment]
> 

I will do this if you abbadon this project

**Comment by atsb** [comment]
So I guess I'll add something quick :)

I don't suppose you know the Steam directory layout for Doom 64?

**Comment by Wolf3s** [comment]
> So I guess I'll add something quick :)
> 
> I don't suppose you know the Steam directory layout for Doom 64?

Yes
