### ISSUE TITLE
[Feature request] automatically locate the Doom 64 WAD

### ISSUE THREAD

**Issue by Xeebleton** [atsb/Doom64EX-Plus#129]
add a feature to automatically locate the Doom 64 WAD from steam, or the user can add their game path to a config.

**Comment by atsb** [comment]
Can do

**Comment by Wolf3s** [comment]
> add a feature to automatically locate the Doom 64 WAD from steam, or the user can add their game path to a config.

#126

**Comment by NightFright2k19** [comment]
A note from my side:
I tend to keep all my iwads in a central location. Here unfortunately I can't do that since the port doesn't recognize the -iwad parameter (if it does, relative paths don't work). I also cannot create a symbolic link to doom64.wad for some reason.

**Comment by atsb** [comment]
It doesn't support an iwad parameter because Doom64 has only ever had one single iwad, there is no need for an iwad parameter.

I'm trying to find a solution that fits everyone, because obviously, I have to factor in macOS, Linux distro's, Windows as well as various embedded systems that also build and run the engine..  it needs to work on all supported platforms (which is a lot).
