### ISSUE TITLE
Some enemies not moving or reacting to player in The Lost Levels...

### ISSUE THREAD

**Issue by PerseusAegis** [atsb/Doom64EX-Plus#166]
Found some enemies that don't move or react to me when seeing me, when I make noise, or even when I shoot them. They simply stand there and can be ignored or killed. Only seemed to happen in The Lost Levels first level from my testing. Seems like it's near window/fences as pictured below. Version 3.6.5.4. 

Update: Also happens in the first level of Fusion of Realities. Seems enemies can get stuck on stairs and suddenly stop moving or reacting at all.

![StuckEnemies1](https://user-images.githubusercontent.com/88910929/214997940-880c83d5-5883-4485-97ec-a4b3ff5cd383.jpg)

**Comment by atsb** [comment]
My guess is that for Lost Levels, their placement was according to the remaster, since it was the only port it was made for.  I'll check FoR, could be some geometry / collision code differences between EX+ and EX/Remaster.  Since EX+ has more of a vanilla collision but not quite to remaster standards.

I'll try to fix it, but since Lost Levels is in the IWAD, I won't be able to change the map itself.  Could be one of those things that just has to be kept, let's see.

**Comment by PerseusAegis** [comment]
Yeah, I did some port comparison for that stairway in FoR. Seems like enemies are meeting a height difference in the last step that blocks them from going up the final stair. Seems what's supposed to happen is the enemies back off and randomly walk around the final step, but in EX+, instead of backing off, they keep trying to force themselves to go up the step and eventually get stuck.

**Comment by atsb** [comment]
Possibly something in the Path Traversal routines in p_map.c

**Comment by atsb** [comment]
Fixed in stable branch
