### ISSUE TITLE
game wont open

### ISSUE THREAD

**Issue by ghost** [atsb/Doom64EX-Plus#179]
i have my asset files in /usr/share/games/doom64ex-plus/ but when I open the game in the engine folder, it wont run and say the iwad is not found. Idk if the readme is being specific enough so I wanted to ask here.
![2023-03-17_22-42](https://user-images.githubusercontent.com/87540491/226080259-e2f407d6-8bfd-4a4f-9d86-6b14f2fa7106.png)

**Comment by ks202005** [comment]
Is it the IWAD from the official 2020 release? Check [my post here](https://github.com/atsb/Doom64EX-Plus/issues/180#issuecomment-1477087603); unfortunately, it's not very clear that the official IWAD is required.

**Comment by atsb** [comment]
> Is it the IWAD from the official 2020 release? Check [my post here](https://github.com/atsb/Doom64EX-Plus/issues/180#issuecomment-1477087603); unfortunately, it's not very clear that the official IWAD is required.

Not very clear?

*Support for the IWAD from Nightdive Studios' official remaster* is on the top part of the readme.  I'm not sure how much more you want it to be visible?  Comic Sans at 70 size font?

> i have my asset files in /usr/share/games/doom64ex-plus/ but when I open the game in the engine folder, it wont run and say the iwad is not found. Idk if the readme is being specific enough so I wanted to ask here. ![2023-03-17_22-42](https://user-images.githubusercontent.com/87540491/226080259-e2f407d6-8bfd-4a4f-9d86-6b14f2fa7106.png)

This is also in the Readme (do people even read the README?)

*GNU/Linux and BSD supports system installations using the compile-time macro -DDOOM_UNIX_INSTALL this will force the software to look for all IWAD and supporting files inside ~/.local/share/doom64ex-plus
Without the macro, it will look inside the current directory that the binary is in.*

**Comment by ks202005** [comment]
> Not very clear?
> 
> _Support for the IWAD from Nightdive Studios' official remaster_ is on the top part of the readme. I'm not sure how much more you want it to be visible? Comic Sans at 70 size font?

Not very clear, as in attempting to use Doom 64 EX Plus as a drop-in replacement for the original EX (which yes, I assumed would work), provides no indication to the user that the IWAD being incompatible is the problem. It just crashes to the desktop without any sort of error dialog box or log file created. So yes, not very clear indeed. 

I wrote my issue the way I did (shortly before realizing what was actually wrong independently of the readme) for indexability for internet searches.. Inevitably, someone is going to want to fix 64EX, find 64EX Plus, have this same issue, and get confused. 

Yes, one should read the readme, but when an existing dependency (in this case, a particular IWAD) has been established, and your project is a fork of the original project, yeah, people are going to assume you can just drag and drop to replace the client and DLLs. The least the client could do is alert users to the fact that the IWAD they have is no longer suitable, instead of apparently shitting itself without giving any sign as to _why_. 

Given the obvious potential for confusion, I really don't understand the hostility.

**Comment by atsb** [comment]
The reason it does not give any indication is due to the various popup API's I would have to implement.  A Win32 popup, a macOS popup and a GNU/Linux GTK3 popup.

It isn't hostility, I am just blunt.

I will add some extra documentation about it to make it clearer to users.
