### ISSUE TITLE
[BUG] Black lines appearing on screen

### ISSUE THREAD

**Issue by owner-w** [atsb/Doom64EX-Plus#196]
Some levels have black lines on them, most of the times are imperceptible because the levels are so dark. The easiest one to notice is that when there is screen wipe effect, you get a black line crossing the screen.

Regular EX does not have this issue.

![Base Profile Screenshot 2023 04 28 - 15 32 13 58](https://user-images.githubusercontent.com/132102644/235249012-a35c604e-3afc-4e3c-826b-69f245f5e800.png)

**Comment by atsb** [comment]
I will check past commits and see when this was introduced

**Comment by atsb** [comment]
I've checked 3 past commits from different dates after major functionality and also the latest one on my machine, I don't get these black lines.  I've tried Windowed, Fullscreen, Linear filtering and Nearest filtering.  No black lines at all.

Since the lines are diagonal, it very well could be display drivers or hardware related since this is almost certainly drawing to the screen.

Also, don't compare again old EX.  It used SDL1.2 and a whole load of ancient code, there has been so many changes over the last 15 months that it is pretty much entirely different now.  EX+ is about as far away as GZDoom is to ZDoom ;)

**Comment by azamorapl** [comment]
I noticed this happens to me too, but disabling the newly added antialiasing option fixes it, perhaps it's related to that?

**Comment by atsb** [comment]
Hmmm you're right.  Weird thing is, Antialiasing on with a HD4600 (integrated GPU) does not show it.  But on my RTX A2000 with it on, it shows.  But switching it off indeed fixes it.

Must be a display driver thing since otherwise I would expect it to show always or not at all regardless of hardware.

**Comment by atsb** [comment]
Fixed in latest release
