### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by jedinjapan** [atsb/Doom64EX-Plus#214]
Just leaving this here in light of the announcement *two days* before I found this project, to let you know the efforts to update and maintain this codebase are appreciated, and while it might seem like it's not widely used at times, it is also because sometimes it is not widely known. EX Plus isn't mentioned on the Doom Wiki for example, which would be a HUGE source of incoming traffic for this project from persons like myself looking to update their classics collection.

Thank you for your work.

**Comment by SilverKeeper** [comment]
It is mentioned. [https://doomwiki.org/wiki/Doom64_EX_Plus](https://doomwiki.org/wiki/Doom64_EX_Plus)

Either way, I also just discovered this fork and I see it as another redemption arc of open-source against these short-lived, mercenary-like works done by NightDive, even if the main dev will stop working on it. 
We can't yield to stagnant software locked behind paywalls, so here's another thank you.

**Comment by atsb** [comment]
> It is mentioned. https://doomwiki.org/wiki/Doom64_EX_Plus
> 
> Either way, I also just discovered this fork and I see it as another redemption arc of open-source against these short-lived, mercenary-like works done by NightDive, even if the main dev will stop working on it. We can't yield to stagnant software locked behind paywalls, so here's another thank you.

Thanks :)

It is indeed a shame that most communities of these games stick to the closed source proprietary releases of these corporations riding on the money grabbing tactic of boomer shooter popularity.  Making closed source versions of open source games should be rallied against instead of being accepted.  In 25 years we are going to have another problem once these releases stop working properly and this time, nobody will have the source code to fix them.

**Comment by bubbleguuum** [comment]
Thanks for working on this project @atsb . As a developer myself, I can understand why you'd want to move on.

**Comment by ks202005** [comment]
It's really unfortunate not many people know about this port. I see someone tried adding information about this project to the PCGamingWiki page for the 2020 re-release but it was removed by a power-editor for having "little to do with this re-release" despite using its IWAD and having ultimately the same origin point as the re-release (original EX), just without massive input lag and ridiculous hardware requirements. 

Honestly, the latest build seems pretty feature complete all things considered, and putting it to rest for now makes sense. You've got a lot of other projects under your belt that are highly important (at least, I consider them important); seriously, you've done a lot for older PC games and I thank you. And not just because you allowed me to play the Lost Levels without feeling like I'm using an early 2000s LCD TV when moving my mouse. :)

**Comment by atsb** [comment]
Thanks, appreciated :)

I love all these games and I feel privileged that I'm able to keep them running, as pristine as possible for future generations to enjoy and to understand the legacy of these titles.  It is important from both an archival point of view and a historical one, I won't completely stop of course, I'll always make sure to provide updates in-case of breakage on system updates etc..  and once SDL3 is released, you can be sure that my projects will be among the first to adopt it.

I'm glad that EX+ is resting well for now, I didn't want to stop until I was completely satisfied with a release, and this was the first one that I legitimately thought "it is pretty damn good right now".  Don't fix what isn't broken :)
