### ISSUE TITLE
Turbo Pinkies on Hardcore! don't seem to want to attack very much 

### ISSUE THREAD

**Issue by JamesC0222** [atsb/Doom64EX-Plus#220]
An entire horde of them seems to just ineffectively headbutt me instead of trying to bite.
https://github.com/atsb/Doom64EX-Plus/assets/81458830/09aed019-30a1-4f6b-8183-4871a04a4800

**Comment by atsb** [comment]
This seems to be expected.  There isn't any particular handling of enemies in turbo mode and so their attack patterns and ai are still operating as if in 'non-turbo' mode.  Which means they may or may not attack before their ai resets their state.  Pinkies are affected the most because they need to come right up to you.
