### ISSUE TITLE
Crusher Crash

### ISSUE THREAD

**Issue by noahastor** [atsb/Doom64EX-Plus#247]
Hello atsb,

Thank you for your hard work. 

[ Version: doom64ex-plus-4.0.0.0-win64 ]

I am getting a crash with latest Steam Doom 64 version on map02 near blue key.
Every time PC is about to get crushed by a ceiling I experience a crash.

I have the following files in the same directory as .exe:

<img width="218" alt="123" src="https://github.com/atsb/Doom64EX-Plus/assets/11727015/5ba012f9-1b1d-4dd7-af9d-e0d3130502c5">

Any help would be much appreciated, thank you!

Have a great week,

PS: I am also experiencing a bug with item/secret count shown as 0 on every map however I saw an issue being reported before.

**Comment by atsb** [comment]
Thanks, I'll take a look

**Comment by Sparc343** [comment]
I will second this, I too experience a complete "crash" (back to desktop) upon "crusher damage" on map 2 in the blue halls - crushers. I had came here to report this and saw it had already been reported so I'm just reiterating that I too have this problem.
A little more specifically, I had full 200 HP, and so it wouldn't have been enough to "kill" me but upon the split second DMG was to be dealt from the crusher; the EXE crashed to desktop...

Edit to add:
It does appear to be any "crushing damage" because it is also doing it on the map "tech center" (map 05)

**Comment by atsb** [comment]
I think this was fixed in commit: https://github.com/atsb/Doom64EX-Plus/commit/9cb04f0f1c68acecd25f404bec369bcc1d9057f3

If not, please reopen.
