### ISSUE TITLE
Music Still Desyncs

### ISSUE THREAD

**Issue by OpenRift412** [atsb/Doom64EX-Plus#57]
I probably should've mentioned this sooner, but I noticed while listening to the intro music, there is a clear desync on the notes, especially with the main melody.

**Comment by thekovic** [comment]
I've tested it and I didn't notice a delay in the intro. What I did notice, however, was that the intro song played completely wrong. It sounds to me like there's a problem with some events that control the volume of the instruments. I made two comparison videos - one sequential and one simultaneous so you can observe and listen yourself (note: N64 footage is from an emulator because I don't have my N64 on hand right now).

https://www.youtube.com/watch?v=jIuHZmPVHj0

https://www.youtube.com/watch?v=kmwruqnimGU

**Comment by atsb** [comment]
Audio on this is a complete strange beast.  I’ll probably have to revert and just make it not affect performance too much.

My audio knowledge is SDL_Mixer only and I don’t really know what I’m doing with fluidsynth at all

**Comment by atsb** [comment]
3.6.5.1 binary should fix this.
